name: push master

on:
  push:
    branches:
      - master

jobs:
  push-tmp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: .github/actions/publish-to-github-page
