name: push develop

on:
  push:
    branches:
      - develop

jobs:
  push-tmp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/publish-to-github-page
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_ACTOR: ${{secrets.GITHUB_ACTOR}}
          GITHUB_REPOSITORY: ${{secrets.GITHUB_REPOSITORY}}
          GITHUB_SHA: ${{secrets.GITHUB_SHA}}
