name: Node CI

on:
  push:
    branches:
      - master

jobs:
  all-in-one:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: npm install, build, and test
      run: |
        npm install
        npm test
        npm run build

    - name: deploy(scp) to server
      run: |
        ls
        echo "${{secrets.DEPLOY_KEY}}" > ~/private.key
        chmod 700 ~/private.key
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P ${{secrets.DEPLOY_HOST_PORT}} -i ~/private.key -r ./dist/* ${{secrets.DEPLOY_HOST_USER}}@${{secrets.DEPLOY_HOST}}:${{secrets.DEPLOY_FOLDER}}

    - name: deploy to github pages
      uses: ./.github/actions/publish-to-github-page
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GITHUB_ACTOR: ${{secrets.GITHUB_ACTOR}}
        GITHUB_REPOSITORY: ${{secrets.GITHUB_REPOSITORY}}
        GITHUB_SHA: ${{secrets.GITHUB_SHA}}
        DIST_FOLDER: ./dist
